var a = 10+2;
console.log(a);
a = 13/2;
console.log(a);
a = 15.5%2;
console.log(a);
a = 10;
a+=2;
console.log(a);
a*=2;
console.log(a);
a++;
console.log(a);
++a;
console.log(a);
var b = 100;
console.log(a==b);
console.log(a>b);
console.log(a<b);
console.log(a!=b);
console.log(a>=b);
console.log(a<=b);
console.log(a<30 && b>10);
console.log(a<30 && b>100);
console.log(a<30 || b>100);