var a = 10;
console.log(typeof(a));
a = "Dhara";
console.log(typeof(a));
a = true;
console.log(typeof(a));
a = null;
console.log(typeof(a));
a = Infinity;
console.log(typeof(a));
a = NaN;
console.log(typeof(a));