var a = "Hello ";
var b = "World";
console.log(a+b);
var c = "Hello";
var d = 2;
console.log(c+d);
var e = "1";
var f = 1;
console.log(e+f);
var g = "1";
var h = 1;
console.log(g-h);
var i = "1";
var j = 5;
console.log(i*j);
var k = "1";
var l = 2;
console.log(k/l);
var m = "1";
var n = 0;
console.log(m>n);